In [13]:
# Import Dependencies

import pandas as pd
import numpy as np
import os

In [14]:
# Load Schedule Data

october_2019 = "2019-2020 Schedule Results/October_2019.csv"
november_2019 = "2019-2020 Schedule Results/November_2019.csv"
december_2019 = "2019-2020 Schedule Results/December_2019.csv"
january_2020 = "2019-2020 Schedule Results/January_2020.csv"
february_2020 = "2019-2020 Schedule Results/February_2020.csv"
march_2020 = "2019-2020 Schedule Results/March_2020.csv"
july_2020 = "2019-2020 Schedule Results/July_2020.csv"
august_2020 = "2019-2020 Schedule Results/August_2020.csv"
september_2020 = "2019-2020 Schedule Results/September_2020.csv"
october_2020 = "2019-2020 Schedule Results/October_2020.csv"

In [15]:
# Read each data set

october19_schedule = pd.read_csv(october_2019)
november19_schedule = pd.read_csv(november_2019)
december19_schedule = pd.read_csv(december_2019)
january20_schedule = pd.read_csv(january_2020)
february20_schedule = pd.read_csv(february_2020)
march20_schedule = pd.read_csv(march_2020)
july20_schedule = pd.read_csv(july_2020)
august20_schedule = pd.read_csv(august_2020)
september20_schedule = pd.read_csv(september_2020)
october20_schedule = pd.read_csv(october_2020)

In [16]:
# Append the 2019 datasets into one large one

df = october19_schedule.append(november19_schedule, ignore_index=True)
df = df.append(december19_schedule, ignore_index=True)
df = df.append(january20_schedule, ignore_index=True)
df = df.append(february20_schedule, ignore_index=True)
df = df.append(march20_schedule, ignore_index=True)
df = df.append(july20_schedule, ignore_index=True)
df = df.append(august20_schedule, ignore_index=True)
df = df.append(september20_schedule, ignore_index=True)
df = df.append(october20_schedule, ignore_index=True)
df.head()

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Notes
0,Tue Oct 22 2019,8:00p,New Orleans Pelicans,122,Toronto Raptors,130,Box Score,OT,20787.0,NaN
1,Tue Oct 22 2019,10:30p,Los Angeles Lakers,102,Los Angeles Clippers,112,Box Score,NaN,19068.0,NaN
2,Wed Oct 23 2019,7:00p,Chicago Bulls,125,Charlotte Hornets,126,Box Score,NaN,15424.0,NaN
3,Wed Oct 23 2019,7:00p,Detroit Pistons,119,Indiana Pacers,110,Box Score,NaN,17923.0,NaN
4,Wed Oct 23 2019,7:00p,Cleveland Cavaliers,85,Orlando Magic,94,Box Score,NaN,18846.0,NaN

In [17]:
# Remove unwanted colummns from each

df.drop(['Start (ET)', 'Unnamed: 6', 'Unnamed: 7', "Attend.", "Notes"], axis=1, inplace=True)
df

                 Date       Visitor/Neutral  PTS          Home/Neutral  PTS.1
0     Tue Oct 22 2019  New Orleans Pelicans  122       Toronto Raptors    130
1     Tue Oct 22 2019    Los Angeles Lakers  102  Los Angeles Clippers    112
2     Wed Oct 23 2019         Chicago Bulls  125     Charlotte Hornets    126
3     Wed Oct 23 2019       Detroit Pistons  119        Indiana Pacers    110
4     Wed Oct 23 2019   Cleveland Cavaliers   85         Orlando Magic     94
...               ...                   ...  ...                   ...    ...
1138   Fri Oct 2 2020            Miami Heat  114    Los Angeles Lakers    124
1139   Sun Oct 4 2020    Los Angeles Lakers  104            Miami Heat    115
1140   Tue Oct 6 2020    Los Angeles Lakers  102            Miami Heat     96
1141   Fri Oct 9 2020            Miami Heat  111    Los Angeles Lakers    108
1142  Sun Oct 11 2020    Los Angeles Lakers  106            Miami Heat     93

[1143 rows x 5 columns]

In [18]:
# Rename columns

df.rename(columns={'Visitor/Neutral': 'Away', 'Home/Neutral': 'Home', 'PTS.1':'Home Score' , 'PTS' : 'Away Score'}, inplace=True)
df

,Date,Away,Away Score,Home,Home Score
0,Tue Oct 22 2019,New Orleans Pelicans,122,Toronto Raptors,130
1,Tue Oct 22 2019,Los Angeles Lakers,102,Los Angeles Clippers,112
2,Wed Oct 23 2019,Chicago Bulls,125,Charlotte Hornets,126
3,Wed Oct 23 2019,Detroit Pistons,119,Indiana Pacers,110
4,Wed Oct 23 2019,Cleveland Cavaliers,85,Orlando Magic,94
...,...,...,...,...,...
1138,Fri Oct 2 2020,Miami Heat,114,Los Angeles Lakers,124
1139,Sun Oct 4 2020,Los Angeles Lakers,104,Miami Heat,115
1140,Tue Oct 6 2020,Los Angeles Lakers,102,Miami Heat,96
1141,Fri Oct 9 2020,Miami Heat,111,Los Angeles Lakers,108
1142,Sun Oct 11 2020,Los Angeles Lakers,106,Miami Heat,93

In [25]:
# Add a win column for the home team as a numeric value

home_winning_condition = [
    (df['Home Score'] > df['Away Score'])
]

home_win_value = [1]

df['Home Win'] = np.select(home_winning_condition, home_win_value)

In [29]:
# Add a margin of victory column

df['Winning Margin'] = df['Away Score'] - df['Home Score']
df['Winning Margin'] = df['Winning Margin'].abs()
df

,Date,Away,Away Score,Home,Home Score,Home Win,Winning Margin
0,Tue Oct 22 2019,New Orleans Pelicans,122,Toronto Raptors,130,1,8
1,Tue Oct 22 2019,Los Angeles Lakers,102,Los Angeles Clippers,112,1,10
2,Wed Oct 23 2019,Chicago Bulls,125,Charlotte Hornets,126,1,1
3,Wed Oct 23 2019,Detroit Pistons,119,Indiana Pacers,110,0,9
4,Wed Oct 23 2019,Cleveland Cavaliers,85,Orlando Magic,94,1,9
...,...,...,...,...,...,...,...
1138,Fri Oct 2 2020,Miami Heat,114,Los Angeles Lakers,124,1,10
1139,Sun Oct 4 2020,Los Angeles Lakers,104,Miami Heat,115,1,11
1140,Tue Oct 6 2020,Los Angeles Lakers,102,Miami Heat,96,0,6
1141,Fri Oct 9 2020,Miami Heat,111,Los Angeles Lakers,108,0,3
1142,Sun Oct 11 2020,Los Angeles Lakers,106,Miami Heat,93,0,13

In [30]:
# Add a total points column

df['Total Points'] = df['Away Score'] + df['Home Score']
df

,Date,Away,Away Score,Home,Home Score,Home Win,Winning Margin,Total Points
0,Tue Oct 22 2019,New Orleans Pelicans,122,Toronto Raptors,130,1,8,252
1,Tue Oct 22 2019,Los Angeles Lakers,102,Los Angeles Clippers,112,1,10,214
2,Wed Oct 23 2019,Chicago Bulls,125,Charlotte Hornets,126,1,1,251
3,Wed Oct 23 2019,Detroit Pistons,119,Indiana Pacers,110,0,9,229
4,Wed Oct 23 2019,Cleveland Cavaliers,85,Orlando Magic,94,1,9,179
...,...,...,...,...,...,...,...,...
1138,Fri Oct 2 2020,Miami Heat,114,Los Angeles Lakers,124,1,10,238
1139,Sun Oct 4 2020,Los Angeles Lakers,104,Miami Heat,115,1,11,219
1140,Tue Oct 6 2020,Los Angeles Lakers,102,Miami Heat,96,0,6,198
1141,Fri Oct 9 2020,Miami Heat,111,Los Angeles Lakers,108,0,3,219
1142,Sun Oct 11 2020,Los Angeles Lakers,106,Miami Heat,93,0,13,199

In [31]:
# Finalized schedule as csv file
file_name = '2019-2020 NBA Schedule Final Results'

df.to_csv(file_name, sep='\t', encoding='utf-8')